<?php

$DATABASE_ADDRESS = $DATABASE_USERNAME = $DATABASE_PASSWORD = $DATABASE_NAME = $DATABASE_CONNECTION = "";

 $DATABASE_ADDRESS = 'localhost';
    $DATABASE_USERNAME = 'nzilanegiven';
    $DATABASE_PASSWORD = '!QAZXSW@#EDC';
    $DATABASE_NAME = 'site_elabvine';

$DATABASE_CONNECTION = mysqli_connect($DATABASE_ADDRESS, $DATABASE_USERNAME, $DATABASE_PASSWORD, $DATABASE_NAME);

?>